# Generated by Django 4.2.6 on 2024-03-29 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('total_calories', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_protein_g', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_carbohydrates_g', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_fats_g', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_saturated_fat_g', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('total_polyunsaturated_fat_g', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('total_monounsaturated_fat_g', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('total_cholesterol_mg', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('total_sodium_mg', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('total_potassium_mg', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('total_fiber_g', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('total_sugar_g', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=255)),
                ('quantity_g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('quantity_oz', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('quantity_number', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=6)),
                ('protein_g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('carbohydrates_g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fats_g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('saturated_fat_g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('polyunsaturated_fat_g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('monounsaturated_fat_g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cholesterol_mg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sodium_mg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('potassium_mg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fiber_g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sugar_g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('vitamin_a_mg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('vitamin_c_mg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('calcium_mg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('iron_mg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_items', to='meals.meal')),
            ],
        ),
    ]
